- name: Create Home Assistant Directory
  ansible.builtin.file:
    path: "{{ homeassistant_docker_path }}"
    owner: "{{ homeassistant_docker_file_owner }}"
    group: "{{ homeassistant_docker_file_group }}"
    state: directory
    mode: 0755

- name: Create Docker Compose File
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homeassistant_docker_path }}/docker-compose.yml"
    owner: "{{ homeassistant_docker_file_owner }}"
    group: "{{ homeassistant_docker_file_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart homeassistant

- name: Validate Docker Compose File
  ansible.builtin.command: docker-compose config --quiet
  args:
    chdir: "{{ homeassistant_docker_path }}"
  changed_when: false

- name: Startup Container
  ansible.builtin.command: >-
    docker-compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ homeassistant_docker_path }}"
  register: homeassistant_container_startup
  changed_when: "'Started' in homeassistant_container_startup.stdout"
